mcc -m...                                   % standalone application
    -o st1_5p_Mackenthun...                 % app name
    -d standalone...                        % output folder
    -R -singleCompThread...                 % use only one computation thread
    -R -nojvm...                            % no java
    -R -nodisplay...                        % no display
    -w enable:specified_file_mismatch...    % enable warnings
    -w enable:repeated_file...
    -w enable:switch_ignored...
    -w enable:missing_lib_sentinel...
    -w enable:demo_license...
    -v...                                   % verbose
    st1uplink_su_monte_carlo.m...           % main file
    -a overwriteDefaultParams.m...
    -a UpdateStruct.m...
    -a st1transmitter.m...
    -a st1receiver.m...
    -a st1receiver_debugplot.m...
    -a SingleUserRXQAM.m...    
    -a initialiseSoftDec.m...
    -a satchan.m...
    -a Acquisition...
    -a ./impl/software/ref-model/mlibrary/pulseshapefilter.m...
    -a ./impl/software/ref-model/mlibrary/scramble_bits.m...
    -a ./impl/software/ref-model/mlibrary/st1interleaver.m...
    -a ./impl/software/ref-model/mlibrary/Acquisition...
    -a ./impl/software/ref-model/mlibrary/Codecs...
    -a ./impl/software/library/phy/bin
